server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ticker-service
              uri: http://company-info-service:8080
              predicates:
                - Path=/api/tickers/**

            - id: company-service
              uri: http://company-info-service:8080
              predicates:
                - Path=/api/companies/**

            - id: news-service
              uri: http://news-service:8080
              predicates:
                - Path=/api/news/**

            - id: historical-service
              uri: http://historical-service:8080
              predicates:
                - Path=/api/historical/**

            - id: notification-service
              uri: http://notification-service:8080
              predicates:
                - Path=/api/notifications/**

            - id: currency-service
              uri: http://currency-service:8080
              predicates:
                - Path=/api/currency/**

            - id: stocks-service
              uri: http://stocks-service:8080
              predicates:
                - Path=/api/stocks/**

            - id: stocks-service-ws
              uri: ws://stocks-service:8080
              predicates:
                - Path=/ws/prices/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        "[http.server.requests]": 25ms,50ms,100ms,200ms,400ms,800ms
    tags:
      application: ${spring.application.name}